Fix disconnect on token expired
GameFuse-PA/front pull request #13
Opened 2023-05-25 06:20 UTC by ShadowZ11

Correction de l'affichage de la page de profil malgré le fait que le token soit expiré.

2023-05-25 06:27 UTC, noeoxycode requested changes

2023-05-25 06:27 UTC, noeoxycode commented on src/app/pages/friends-page/friends-page.component.ts
> +      if (!this.authServices.user?.access_token || TokenUtils.isTokenExpired(this.authServices.user?.access_token)) {
A ajouter dans la méthode utils

2023-05-25 06:27 UTC, noeoxycode commented on src/app/pages/profilpage/profil-page.component.ts
> +        if (!this.authServices.user?.access_token) {
Même problème

2023-05-26 10:19 UTC, Pbonnamy requested changes

2023-05-26 10:19 UTC, Pbonnamy commented on src/app/utils/tokenUtils.ts
> +}
a delete

2023-05-26 10:19 UTC, Pbonnamy commented on package.json
> +    "jwt-decode": "^3.1.2",
a delete

2023-05-26 10:31 UTC, Pbonnamy approved these changes

2023-05-26 10:31 UTC, Pbonnamy approved these changes

2023-05-26 10:34 UTC, noeoxycode approved these changes

2023-05-26 10:48 UTC, merged