Feature/create party
GameFuse-PA/front pull request #30
Opened 2023-06-25 23:42 UTC by ShadowZ11

Création d'une partie + refacto room à l'intérieur de des dossiers game session + petit fix de l'ui pour la liste des sessions de jeu

2023-07-04 21:12 UTC, Pbonnamy requested changes

2023-07-04 21:12 UTC, Pbonnamy commented on src/app/components/game-session/create-game-session-dialog/create-game-session-dialog.component.ts
> +        console.log(err);
a enlever + tu peux gérer le loading ici

2023-07-04 21:12 UTC, Pbonnamy commented on src/app/components/game-session/create-game-session-dialog/create-game-session-dialog.component.ts
> +  protected readonly FormControl = FormControl;
a remonter en haut du fichier si t'en a besoin

2023-07-04 21:12 UTC, Pbonnamy commented on src/app/components/game-session/create-game-session-dialog/create-game-session-dialog.component.html
> +                !session.game ||
2 fois la meme condition

2023-07-04 21:12 UTC, Pbonnamy commented on src/app/models/game-session.model.ts
>  }
1 fichier par entité

2023-07-04 22:14 UTC, ShadowZ11 commented on src/app/components/game-session/create-game-session-dialog/create-game-session-dialog.component.ts
> +  protected readonly FormControl = FormControl;
ça ça se rajoute toujours tout seul je sais pas pk, je l'ai enlevé parce que j'en ai pas besoin

2023-07-04 22:17 UTC, ShadowZ11 commented on src/app/components/game-session/create-game-session-dialog/create-game-session-dialog.component.ts
> +        console.log(err);
ça je préfère pas trop toucher en vrai parce que c'est noé qui va ensuite se baser sur ça pour le module du chat

2023-07-04 22:17 UTC, ShadowZ11 commented on src/app/components/game-session/create-game-session-dialog/create-game-session-dialog.component.html
> +                !session.game ||
j'ai retiré la partie dans l'appel du onCreate pour le laisser la dedans

2023-07-05 20:53 UTC, Pbonnamy approved these changes

2023-07-05 21:40 UTC, merged