Feature/live chat
GameFuse-PA/front pull request #7
Opened 2023-05-13 16:48 UTC by noeoxycode

Possibilité de créer une room depuis /chatHome
pour rejoindre la room il faut être connecté. Un bouton de copie d'url dans le presse papier est disponible. Pour rejoindre il suffit de rentrer l'url de la room.
On peut échanger des chats.
Les chats ne sont pas encore sauvegardés en db même si le code est globalement développé. A ne pas prendre en compte pour la mr (c'est commenté)

2023-05-14 17:07 UTC, Pbonnamy submitted a review, later dismissed

2023-05-17 09:01 UTC, Pbonnamy reviewed
waiting for ShadowZ11 approval

2023-05-17 09:04 UTC, ShadowZ11 commented on src/app/modules/chat/components/chat-input/chat-input.component.html
> +</div-->
ils comptent te servirent ce bout de code plus tard, si non tu peux le supprimer

2023-05-17 09:04 UTC, ShadowZ11 commented on src/app/services/chat/chat.service.ts
> +    console.log(URL + `/createRoom/${roomId}`)
retire les console.log, dans le cas ici ils servent pas trop à grand chose

2023-05-17 09:04 UTC, ShadowZ11 commented on src/app/modules/call/data/media-icon.ts
> +    soundOffIconUrl: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAABmJLR0QA/wD/AP+gvaeTAAAAkElEQVRIie2Suw2AMAwFHzADESvCArSMRsMCUDBOKDCSZZmggC1R5Ko4tt4pH6BgzOQdHr3DXQQ83Fwgw00
Je te recommande plutôt que de mettre des image en base64 si c'est du statique pour le front, de mettre les images en .png .jpg dans le dossier assets et de les récupérer, parce que si un jour tu te décide à remplacer les icônes, faut que tu les reformates toutes en base64

2023-05-17 09:19 UTC, Pbonnamy requested changes
`uuid@3.4.0: Please upgrade  to version 7 or higher`
dépendance à upgrade, j'ai pas tout regardé mais je suis pas sur que ce soit normal que tu génère des id au niveau du front

2023-05-23 12:24 UTC, Pbonnamy approved these changes

2023-05-23 12:24 UTC, merged